# This file was generated by GoReleaser. DO NOT EDIT.
cask "tq" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "6ffd545a6f01413ff38e49e62b07354c6f6c9ce76e340819e9d9445a4643affc"
      url "https://github.com/tentaqles/tentaqles/releases/download/v#{version}/tq_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "47a9db0d1de7ee33ed3288e0dddf287364effe25996c2cc7d73fdd89e3800960"
      url "https://github.com/tentaqles/tentaqles/releases/download/v#{version}/tq_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "39f62901479164e55b486d0ff62a591f427436a114923cd0576b6cbfc0a1139e"
      url "https://github.com/tentaqles/tentaqles/releases/download/v#{version}/tq_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5bdf60e0680c096dd274dfb852a4d79b1d3541cf2eb0ad2263e4d6d0fa8c2459"
      url "https://github.com/tentaqles/tentaqles/releases/download/v#{version}/tq_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tq"
  desc "One terminal identity per workspace folder"
  homepage "https://tentaqles.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tq"

  # No zap stanza required
end
