# This file was generated by GoReleaser. DO NOT EDIT.
cask "tq" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "5e5e8bb5905176e3c2e478fa65c12a3f7d98959efdca954392df5bd58fead1bb"
      url "https://github.com/tentaqles/tentaqles/releases/download/v#{version}/tq_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "65ccfb481f172d73489b0207d38bc92d20302ca268824bb9c9b7f47561adab8d"
      url "https://github.com/tentaqles/tentaqles/releases/download/v#{version}/tq_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "610bc1148583ce5287f3ffa679da5f310fa9c972e29780271d7128134855be40"
      url "https://github.com/tentaqles/tentaqles/releases/download/v#{version}/tq_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0f5aba2f3d54a75274798586a053c589dd7eabe89c81ca6683c6783baf93c979"
      url "https://github.com/tentaqles/tentaqles/releases/download/v#{version}/tq_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tq"
  desc "One terminal identity per workspace folder"
  homepage "https://tentaqles.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tq"

  # No zap stanza required
end
