# This file was generated by GoReleaser. DO NOT EDIT.
cask "tq" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "8a52174ffd9546d3b44cc4b321927afa7c14ebcbd2c2dd4686779c4c7c1e4444"
      url "https://github.com/tentaqles/tentaqles/releases/download/v#{version}/tq_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0c5068869a477c48257bb29e95da14a7ad95f40d25dd3fe78c05b09c94340014"
      url "https://github.com/tentaqles/tentaqles/releases/download/v#{version}/tq_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "27933d5b87fce31856d76b2ba7e44ececf28921f8eed18371b0f2e0baaebe8e4"
      url "https://github.com/tentaqles/tentaqles/releases/download/v#{version}/tq_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "39ee81bc5043f5affc989f327c996aecc9192f32e3b6c699268db72d3457ba03"
      url "https://github.com/tentaqles/tentaqles/releases/download/v#{version}/tq_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tq"
  desc "One terminal identity per workspace folder"
  homepage "https://tentaqles.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tq"

  # No zap stanza required
end
